project:
  type: website
  resources:
    - keybase.txt
    - resume.pdf
    - cv.pdf

website:
  title: "Esben Lykke"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications/publications.qmd
      - text: "Presentations"
        href: presentations.qmd
      - text: "Rando"
        href: rando.qmd
  page-footer:
    left: "© Copyright 2023 Esben Lykke."
format:
  html:
    page-layout: full
    theme:
      dark: slate
      light: yeti
    toc: true